INSERT INTO EMPLOYEE (id, name) VALUES (1, 'DHONI');
INSERT INTO EMPLOYEE (id, name) VALUES (2, 'KHOLI');
INSERT INTO EMPLOYEE (id, name) VALUES (3, 'RAFLEE');
INSERT INTO EMPLOYEE (id, name) VALUES (4, 'DENNIS');